apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: sktrinh12/fastapi-k8s:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: py-app
  labels:
    service: py-app
spec:
  selector:
    app: py-app
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 8000
